version: '1'
services:
  source:
    image: chitchat_source:1.0.0
    volumes:
      - ./source:/app
      - /app/node_modules
    ports:
      - "3000:4200"
  server:
    image: chitchat_server:1.0.0
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
