# Generated by Django 4.2.7 on 2023-12-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChitChatUser',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_username', models.CharField(default='', max_length=20, unique=True)),
                ('User_password', models.CharField(default='', max_length=10)),
                ('User_fullname', models.CharField(max_length=20)),
                ('User_bio', models.CharField(max_length=100)),
                ('User_photo', models.ImageField(default=None, upload_to='')),
                ('User_loggedStatus', models.BooleanField(default=False)),
                ('User_premiumStatus', models.BooleanField(default=False)),
                ('User_premiumDaysLeft', models.IntegerField(default=0)),
                ('User_lastSeen', models.DateTimeField(auto_now=True)),
                ('blockList', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Message_id', models.AutoField(primary_key=True, serialize=False)),
                ('Message_text', models.CharField(max_length=500)),
                ('Message_SendTime', models.DateTimeField(auto_now_add=True)),
                ('Message_photo', models.ImageField(upload_to='')),
                ('Message_Voice', models.FileField(upload_to='')),
                ('Message_isEdited', models.BooleanField(default=False)),
                ('Message_isForwarded', models.BooleanField(default=False)),
                ('Message_originalSenderForwardCase', models.CharField(max_length=20)),
            ],
        ),
    ]
