# Generated by Django 4.2.7 on 2023-12-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Message_receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_message_set', to='User_test.chitchatuser'),
        ),
        migrations.AddField(
            model_name='message',
            name='Message_sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_message_set', to='User_test.chitchatuser'),
        ),
    ]
