# Generated by Django 4.2.7 on 2023-12-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_test', '0002_message_message_receiver_message_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Message_type',
            field=models.CharField(choices=[('text', 'text_message'), ('photo', 'photo_message'), ('voice', 'voice_message')], default='text', max_length=10),
        ),
    ]
