# Generated by Django 4.2.7 on 2023-12-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_test', '0004_alter_chitchatuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitchatuser',
            name='User_password',
        ),
        migrations.AddField(
            model_name='chitchatuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='chitchatuser',
            name='password',
            field=models.CharField(default='111111', max_length=10),
        ),
    ]
