# Generated by Django 4.2.7 on 2023-12-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_test', '0005_remove_chitchatuser_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitchatuser',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
    ]
