# Generated by Django 4.2.7 on 2023-12-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_test', '0006_alter_chitchatuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chitchatuser',
            old_name='User_bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='chitchatuser',
            old_name='User_fullname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='chitchatuser',
            old_name='User_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='chitchatuser',
            old_name='User_lastSeen',
            new_name='lastSeen',
        ),
        migrations.RenameField(
            model_name='chitchatuser',
            old_name='User_loggedStatus',
            new_name='loggedStatus',
        ),
        migrations.RenameField(
            model_name='chitchatuser',
            old_name='User_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='chitchatuser',
            old_name='User_premiumDaysLeft',
            new_name='premiumDaysLeft',
        ),
        migrations.RenameField(
            model_name='chitchatuser',
            old_name='User_premiumStatus',
            new_name='premiumStatus',
        ),
        migrations.RenameField(
            model_name='chitchatuser',
            old_name='User_username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='chitchatuser',
            name='access',
            field=models.BooleanField(default=True),
        ),
    ]
