---
name: E2E tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/included:3.8.3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        run: cypress run
